## Great Circle Calculation

Overview:
- [ ] [gc_aangle](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_aangle.shtml):  Finds the acute angle between two great circles on the globe. 
- [ ] [gc_clkwise](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_clkwise.shtml):  Tests clockwise/counterclockwise ordering of points on spherical polygon. 
- [ ] [gc_dangle](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_dangle.shtml):  Finds the directed angle between two great circles having a specified intersection point. 
- [ ] [gc_inout](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_inout.shtml):  Determines if a list of lat/lon specified points are inside or outside of spherical lat/lon polygon(s). 
- [ ] [gc_latlon](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_latlon.shtml): Finds the great circle distance (true surface distance) between two points on the globe and interpolates points along the great circle. 
- [ ] [gc_onarc](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_onarc.shtml):  Determines if a point on the globe lies on a specified great circle arc. 
- [ ] [gc_pnt2gc](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_pnt2gc.shtml):  Finds the angular distance from a point to a great circle. 
- [ ] [gc_qarea](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_qarea.shtml):  Finds the area of a quadrilateral patch on the unit sphere. 
- [ ] [gc_tarea](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_tarea.shtml):  Finds the area of a triangular patch on the unit sphere. 

In [17]:
import numpy as np

In [18]:
# Convert Latitude, Longitude, Radius to a Cartesian Coordinate System

boulder_lat = 40.0150
boulder_lon = -105.2705
boston_lat = 42.3601
boston_lon = -71.0589

earth_radius = 6378137  # meters, WSG-84: https://gscommunitycodes.usf.edu/geoscicommunitycodes/public/geophysics/Gravity/earth_shape.php

## Cartesian Coordinates

Cartesian coordinates describe points in space based on perpendicular axis lines that meet at a singlle point of orign, where any point's position is described based on the distance to the orgin along xyz axis

In [19]:
def latlon_to_cartesian_coords(latitude=None, longitude=None, radius=None):
    cart_x = radius * np.cos(latitude) * np.cos(longitude)
    cart_y = radius * np.cos(latitude) * np.sin(longitude)
    cart_z = radius * np.sin(latitude)
    return cart_x, cart_y, cart_z

In [20]:
# Boulder Cartesian Coordinates
boulder_coords = {"latitude": boulder_lat, "longitude": boulder_lon}
cart_x, cart_y, cart_z = latlon_to_cartesian_coords(boulder_lat, boulder_lon, earth_radius)
boulder_coords["cart_x"] = cart_x
boulder_coords["cart_y"] = cart_y
boulder_coords["cart_z"] = cart_z
boulder_coords

{'latitude': 40.015,
 'longitude': -105.2705,
 'cart_x': -117382.37626000034,
 'cart_y': -4323034.280763086,
 'cart_z': 4688094.237092482}

In [21]:
# Boston Cartesian Coordinates
boston_coords = {"latitude": boston_lat, "longitude": boston_lon}
cart_x, cart_y, cart_z = latlon_to_cartesian_coords(boston_lat, boulder_lon, earth_radius)
boston_coords["cart_x"] = cart_x
boston_coords["cart_y"] = cart_y
boston_coords["cart_z"] = cart_z
boston_coords

{'latitude': 42.3601,
 'longitude': -71.0589,
 'cart_x': -8894.608669512068,
 'cart_y': -327576.41664284625,
 'cart_z': -6369713.193540589}

## Spherical Coordinates

Spherical coordinates describe points in space based on three values: radial distance (rho, r) along the radial line between point and the origin, polar angle (theta, θ) between the radial line and the polar axis, and azimuth angle (phi, φ) which is the angle of rotation of the radial line around the polar axis. With a fixed radius, the 3-point coordinates (r, θ, φ) provide a coordiante along a sphere

- Radial distance: distance from center to surface of sphere
- Polar angle: angle between radial line and polar axis
- Azimuth angle: angle around polar axis

<p align="center">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Sphericalcoordinates.svg/1024px-Sphericalcoordinates.svg.png" alt="Spherical Coordinate Description from Wikipedia" width=400 />
</p>

In [23]:
# https://math.libretexts.org/Courses/Mount_Royal_University/MATH_2200%3A_Calculus_for_Scientists_II/7%3A_Vector_Spaces/5.7%3A_Cylindrical_and_Spherical_Coordinates
def cartestian_to_spherical(cart_x, cart_y, cart_z):
    # Convert from rectangular coordinates to spherical coordinates
    rho = np.sqrt(cart_x**2 + cart_y**2 + cart_z**2)
    theta = np.arctan(cart_y/cart_x)
    phi = np.arccos(cart_z / rho)
    return rho, theta, phi    

In [24]:
# Boulder Spherical Coordinates
rho, theta, phi = cartestian_to_spherical(boulder_coords["cart_x"], boulder_coords["cart_y"], boulder_coords["cart_z"])
boulder_coords["rho"] = rho
boulder_coords["theta"] = theta
boulder_coords["phi"] = phi
boulder_coords

{'latitude': 40.015,
 'longitude': -105.2705,
 'cart_x': -117382.37626000034,
 'cart_y': -4323034.280763086,
 'cart_z': 4688094.237092482,
 'rho': 6378137.0,
 'theta': 1.5436502220529718,
 'phi': 0.7450918301275852}

In [25]:
# Boston Spherical Coordinates
rho, theta, phi = cartestian_to_spherical(boston_coords["cart_x"], boston_coords["cart_y"], boston_coords["cart_z"])
boston_coords["rho"] = rho
boston_coords["theta"] = theta
boston_coords["phi"] = phi
boston_coords

{'latitude': 42.3601,
 'longitude': -71.0589,
 'cart_x': -8894.608669512068,
 'cart_y': -327576.41664284625,
 'cart_z': -6369713.193540589,
 'rho': 6378137.0,
 'theta': 1.5436502220529718,
 'phi': 3.0901918301275884}

https://www.nosco.ch/mathematics/en/great-circle.php

In [39]:
## Return spherical and cartesian coordiantes dictionary for a new point

def return_all_coords(latitude=None, longitude=None):
    new_coords_dict = {"latitude": latitude, "longitude": longitude}
    cart_x, cart_y, cart_z = latlon_to_cartesian_coords(latitude, longitude, earth_radius)
    new_coords_dict["cart_x"] = cart_x
    new_coords_dict["cart_y"] = cart_y
    new_coords_dict["cart_z"] = cart_z
    rho, theta, phi = cartestian_to_spherical(new_coords_dict["cart_x"], new_coords_dict["cart_y"], new_coords_dict["cart_z"])
    new_coords_dict["rho"] = rho
    new_coords_dict["theta"] = theta
    new_coords_dict["phi"] = phi
    return new_coords_dict

In [27]:
# pip install uxarray
# pip install shapely
# pip install Pillow
# pip install pyparsing
# pip install kiwisolver
# pip install dask
# python -m pip install "dask[dataframe]"
# pip install fsspec
import uxarray as ux

## gc_onarc: Determines if a point on the globe lies on a specified great circle arc

``
uxarray.grid.arcs.point_within_gca(pt, gca_cart, is_directed=False)
``
- pt (numpy.ndarray (float)) – Cartesian coordinates of the point
- gca_cart (numpy.ndarray of shape (2, 3), (np.float or gmpy2.mpfr)) – Cartesian coordinates of the Great Circle Arc (GCR).

### Great Circle Arc

In [47]:
# Great Circle Arc formed by cartesian coordinates of two points (Boulder -> Boston)
boulder_point = np.array([boulder_coords["cart_x"], boulder_coords["cart_y"], boulder_coords["cart_z"]])
boston_point = np.array([boulder_coords["cart_x"], boulder_coords["cart_y"], boulder_coords["cart_z"]])

great_circle_arc = np.array([boulder_point, boston_point])
print(great_circle_arc.shape)
great_circle_arc

(2, 3)


array([[ -117382.37626   , -4323034.28076309,  4688094.23709248],
       [ -117382.37626   , -4323034.28076309,  4688094.23709248]])

### Point along the great circle arc from Boulder to Boston: Cloverdale
Arc determined via [great circle map](https://www.greatcirclemap.com/roadmap?routes=DEN-BOS) between DIA and Logan Airport

In [41]:
# Point along the great circle arc: Cloverdale
cloverdale_lat = 38.8055
cloverdale_lon = -123.0172
cloverdale_coords = return_all_coords(cloverdale_lat, cloverdale_lon)
point_on_arc = np.array([cloverdale_coords["cart_x"], cloverdale_coords["cart_y"], cloverdale_coords["cart_z"]])
point_on_arc

array([-2513713.48229094,  1357253.48920046,  5702608.09505361])

In [43]:
does_point_lie_on_arc = ux.grid.arcs.point_within_gca(point_on_arc, great_circle_arc)
print(f"Does the point lie on the great circle = {does_point_lie_on_arc}")

Does the point lie on the great circle = True


### Point NOT along the great circle arc from Boulder to Boston: Wichita  

In [48]:
# Point NOT along the great circle arc: Wichita
wichita_lat = 37.6872
wichita_lon = -97.3301
wichita_coords = return_all_coords(wichita_lat, wichita_lon)
point_on_arc = np.array([wichita_coords["cart_x"], wichita_coords["cart_y"], wichita_coords["cart_z"]])
point_on_arc

array([-6366484.73786982,  -377798.47782279,   -75973.57036748])

In [49]:
does_point_lie_on_arc = ux.grid.arcs.point_within_gca(point_on_arc, great_circle_arc)
print(f"Does the point lie on the great circle = {does_point_lie_on_arc}")

Does the point lie on the great circle = False


### Point ALMOST along the great circle arc from Boulder to Boston: Omaha   

In [50]:
# Point NOT along the great circle arc: Omaha
omaha_lat = 37.6872
omaha_lon = -97.3301
omaha_coords = return_all_coords(omaha_lat, omaha_lon)
point_on_arc = np.array([omaha_coords["cart_x"], omaha_coords["cart_y"], omaha_coords["cart_z"]])
point_on_arc

array([-6366484.73786982,  -377798.47782279,   -75973.57036748])

In [51]:
does_point_lie_on_arc = ux.grid.arcs.point_within_gca(point_on_arc, great_circle_arc)
print(f"Does the point lie on the great circle = {does_point_lie_on_arc}")

Does the point lie on the great circle = False


> A great circle is a section of a sphere that contains a diamter of the sphere...A great circle becomes a straight line in a gnomoni c projection
> To find the great circle (geodesic) distance between two points located at latitude `delta` and longitude `lambda` of (delta_1, lamba_1) and (delta_2, lambda_2) on a sphere of radius a

[Wolfram MathWorld](https://mathworld.wolfram.com/GreatCircle.html)

1. Convert spherical coordinates to Cartesian coordinates using:

```
        | cos(lambda_i) * cos(delta_i) |
r_i = a | sin(lambda_i) * cos(delta_i) |
        |        sin(delta_i)          |
```
2. Find the angle `alpha` between r1 and r2 using the dot product
```
cos(alpha) = r_1_hat * r_2_hat
cos(alpha) = cos(delta_1) * cos(delta_2) * cos(lambda_1 - lambda_2) + sin(delta_1) * sin(delta_2)
```
3. The great circle distance is then: where a = 6378 km
```
d = a * cos^-1[cos(delta_1) * cos(delta_2) * cos(lambda_1 - lambda_2) + sin(delta_1) * sin(delta_2)]
```

- [gc_aangle](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_aangle.shtml):  Finds the acute angle between two great circles on the globe. 
- [gc_clkwise](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_clkwise.shtml):  Tests clockwise/counterclockwise ordering of points on spherical polygon. 
- [gc_dangle](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_dangle.shtml):  Finds the directed angle between two great circles having a specified intersection point. 
- [gc_inout](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_inout.shtml):  Determines if a list of lat/lon specified points are inside or outside of spherical lat/lon polygon(s). 
- [gc_latlon](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_latlon.shtml): Finds the great circle distance (true surface distance) between two points on the globe and interpolates points along the great circle. 
- [gc_onarc](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_onarc.shtml):  Determines if a point on the globe lies on a specified great circle arc. 
- [gc_pnt2gc](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_pnt2gc.shtml):  Finds the angular distance from a point to a great circle. 
- [gc_qarea](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_qarea.shtml):  Finds the area of a quadrilateral patch on the unit sphere. 
- [gc_tarea](https://www.ncl.ucar.edu/Document/Functions/Built-in/gc_tarea.shtml):  Finds the area of a triangular patch on the unit sphere. 

In [ ]:
from pyproj import Geod
geodesic = Geod(ellps="WGS84")

## gc_aangle

This function finds the acute angle between two great circles, given two pairs of points on the globe that define two arcs. 

### Input:
Latitudes and longitudes, in degrees, of vertices. The first two pairs of lat/lon values specify vertices of an arc of one great circle and the second two pairs specify the vertices of the second circle. These can be multi-dimensional arrays, but the rightmost dimension size must be 4 for specifying the vertices of the two arcs. If lat and lon have more than one dimension, then they must agree in number of dimensions and dimension sizes.
Return value
### Output
The acute angle, in degrees, between the great circles defined by the arcs as describe above. This will be a non-negative value. If the input arrays are singly dimensioned, then the return value will be a scalar. If the input arrays are multi-dimensional, then the returned array will have one less dimension than the number of dimensions of the input arrays and the dimension sizes of the returned array will agree with those of the input arrays up through their penultimate dimension. The return value will be of type double if either of the input arguments is of type double and type float otherwise.

In [ ]:
aangle = ((0.0,  0.0, 0.0,  10.0), (0.0, 10.0, 0.0,   0.0))
arc_1_start  = (aangle[0][0], aangle[1][0])
arc_1_end    = (aangle[0][1], aangle[1][1])
arc_2_start  = (aangle[0][2], aangle[1][2])
arc_2_end    = (aangle[0][3], aangle[1][3])

print(arc_1_start) # (lat, lon)
print(arc_1_end)   # (lat, lon)

print(arc_2_end)   # (lat, lon)
print(arc_2_start) # (lat, lon)

#fwd_bearing, rvs_bearing, distance_m = geodesic.inv(lon_start, lat_start, lon_end, lat_end)
fwd_bearing, rvs_bearing, distance_m = geodesic.inv(arc_1_start[1],
                                                    arc_1_start[0],
                                                    arc_1_end[1],
                                                    arc_1_end[0])
print(f"forward bearing = {fwd_bearing} degrees")
print(f"reverse bearing = {rvs_bearing} degrees")
print(f"distance_m = {distance_m/1000} km")